# Generated by Django 5.2.9 on 2026-08-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0010_add_query_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Hex color, e.g. #d93025', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='election_logos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='election',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Hex color, e.g. #1a73e8', max_length=7, null=True),
        ),
    ]
