# Generated by Django 5.2.9 on 2026-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0011_add_election_branding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voter_password',
        ),
        migrations.AddField(
            model_name='voter',
            name='login_token_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='login_token_issued_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='login_token_used_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_password_hash',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
